<?php

declare(strict_types=1);

namespace App\Services;

use App\Models\Scene;

final class SceneScriptPrompt
{
    /**
     * Rotating opening-style hints keyed by scene order. Each scene is generated by an
     * independent LLM call that cannot see the others, so without a deterministic nudge the
     * model defaults to the same "you are standing…" opening every time. Rotating the entry
     * style forces variety across scenes.
     *
     * @var list<string>
     */
    private const OPENING_STYLES = [
        'Open in the middle of an action or movement — someone doing something.',
        'Open on a line of dialogue: something a person says, shouts, or whispers.',
        'Open on one vivid object or detail, then widen out from it.',
        'Open with a decision or dilemma facing someone in the scene.',
        'Open with a sound, a smell, or a sudden change in the surroundings.',
    ];

    public static function system(): string
    {
        return 'You write tight, vivid history narration in 80-150 words per scene. '
             .'Only use facts from the provided source. If uncertain, omit — never invent. '
             .'Write in second person to put the student inside the moment. '
             .'Critically: VARY how each scene opens — never begin with "you are standing", and '
             .'do not reuse the same sensory formula (e.g. "the air thick with…") across scenes. '
             .'No headings, no scene numbers, no meta-commentary — pure narration prose only.';
    }

    /** Deterministic opening-style hint for a scene so independent generations stay varied. */
    public static function openingHintFor(int $order): string
    {
        $index = ($order - 1) % count(self::OPENING_STYLES);

        return self::OPENING_STYLES[max(0, $index)];
    }

    public static function user(Scene $scene, string $sourceText, string $tone, string $grade): string
    {
        $brief = $scene->lesson->outline['scene_briefs'][$scene->order - 1] ?? [];
        $year = $scene->year ?? ($brief['year'] ?? 'unknown year');
        $location = $scene->location ?? ($brief['location'] ?? 'unknown location');

        $beat = $brief['beat'] ?? 'continue the story';
        $purpose = $brief['scenePurpose'] ?? '';
        $viewerPos = $brief['viewerPosition'] ?? '';
        $facts = $brief['historicalFacts'] ?? [];
        $visual = $brief['visualEvidence'] ?? [];
        $avoid = $brief['avoidList'] ?? [];

        $factsBlock = $facts ? "Historical facts to include:\n".self::bulletList($facts) : '';
        $visualBlock = $visual ? "Visual details in this scene:\n".self::bulletList($visual) : '';
        $avoidBlock = $avoid ? "Do NOT reference:\n".self::bulletList($avoid) : '';
        $posBlock = $viewerPos ? "Student viewpoint: {$viewerPos}" : '';
        $purposeBlock = $purpose ? "Learning goal: {$purpose}" : '';
        $openingHint = self::openingHintFor($scene->order);

        return <<<USR
Scene {$scene->order} — {$year}, {$location}
Beat: {$beat}
{$purposeBlock}
{$posBlock}
Grade level: {$grade}
Tone: {$tone}

Opening style for this scene: {$openingHint}

{$factsBlock}

{$visualBlock}

{$avoidBlock}

Source text (authoritative — only use facts from here):
"""
{$sourceText}
"""

Write the narration for THIS scene only. 80-150 words. Plain prose, second person. Do NOT begin with "you are standing". No headings, no scene number.
USR;
    }

    private static function bulletList(array $items): string
    {
        return implode("\n", array_map(fn ($i) => "- {$i}", $items));
    }
}
