<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('lessons', function (Blueprint $table) {
            // Optional teacher notes / special requirements
            $table->text('details')->nullable()->after('grade_level');

            // Make title nullable — now generated by the LLM, not entered by the teacher
            $table->string('title', 255)->nullable()->change();

            // Change tone from enum to free-text string so teachers can describe voice/personality
            $table->string('tone', 150)->nullable()->change();
        });
    }

    public function down(): void
    {
        Schema::table('lessons', function (Blueprint $table) {
            $table->dropColumn('details');
            $table->string('title', 255)->nullable(false)->change();
            $table->enum('tone', ['serious', 'dramatic', 'playful', 'inspiring'])->default('dramatic')->change();
        });
    }
};
