<?php

declare(strict_types=1);

/** De reis van Abel Tasman — exported from lesson WMDIF8 (6 scenes). */
return [
    'key' => 'De reis van Abel Tasman (1642-1643)',
    'title' => 'De reis van Abel Tasman',
    'subject' => 'history',
    'grade_level' => 'K-7',
    'tone' => 'adventurous',
    'map_style' => 'satellite',
    'map_relief' => 6,
    'game_config' => [
        'voyage' => 'tasman-1642',
        'route_line' => [
            'enabled' => true,
            'color' => '#a51228',
            'opacity' => 0.9,
            'thickness' => 9.5,
            'wobble' => 0.3,
            'curve' => 'bezier',
        ],
        'voyage_map' => [
            'cities' => false,
            'borders' => true,
            'labels' => true,
            'label_color' => '#3a2c1a',
            'label_size' => 1,
            'city_color' => '#3a2c1a',
            'city_size' => 1,
            'border_color' => '#5b4a36',
            'border_width' => 0.6,
            'border_opacity' => 0.3,
            'ship_scale' => 2.2,
            'ship_anchored' => true,
            'motion' => 100,
            'info_position' => 'bottom',
            'ocean_zoom' => 15,
            'cam_dolly_arrival' => true,
            'fog_auto' => false,
        ],
        'voyage_def' => [
            'id' => 'tasman-1642',
            'name' => 'Abel Tasman',
            'years' => '1642–1643',
            'qid' => 'Q42188',
            'year_start' => 1642,
            'year_end' => 1643,
            'show_from' => 1638,
            'show_to' => 1720,
            'label_at' => 8,
            'waypoints' => [
                [106.9, -5.9],
                [105.85, -6.15],
                [105, -6.9],
                [103.6, -9.5],
                [90, -14],
                [70, -18],
                [57.5, -20.2],
                [70, -35],
                [95, -44],
                [125, -45.5],
                [146.3, -44.4],
                [149, -43.8],
                [160, -42.8],
                [169.5, -42],
                [171.8, -40.9],
                [173.408, -39.977],
                [173.3, -39.4],
                [173.2, -38],
                [172.8, -36],
                [172.6, -34],
                [176, -28],
                [181, -22.5],
                [184.8, -21.1],
                [182.5, -19.5],
                [177.2, -18.9],
                [172, -14.5],
                [166, -10.5],
                [160.8, -7.6],
                [155, -4.2],
                [153.6, -3.4],
                [149.5, -3],
                [144, -2.2],
                [137.5, -0.8],
                [131.8, 0.6],
                [128.9, 2.5],
                [126.6, 3.2],
                [123.5, 2.4],
                [120.2, 2],
                [118.6, -0.3],
                [117.8, -2.6],
                [117.2, -4.9],
                [114.5, -6.1],
                [110.5, -5.85],
                [108.5, -5.55],
                [106.9, -5.85],
            ],
            'fleet' => [
                [
                    'name' => 'Heemskerck',
                    'masts' => 3,
                    'flagship' => true,
                    'model' => '/timemap/assets/ship.fbx',
                ],
                [
                    'name' => 'Zeehaen',
                    'masts' => 3,
                    'flagship' => false,
                ],
            ],
            'legs' => [
                [
                    'depart' => '1642-08-14',
                    'arrive' => '1642-09-05',
                    'wp' => [0, 6],
                ],
                [
                    'depart' => '1642-10-08',
                    'arrive' => '1642-11-24',
                    'wp' => [6, 10],
                ],
                [
                    'depart' => '1642-12-04',
                    'arrive' => '1642-12-13',
                    'wp' => [10, 15],
                ],
                [
                    'depart' => '1642-12-18',
                    'arrive' => '1643-01-21',
                    'wp' => [15, 22],
                ],
                [
                    'depart' => '1643-02-01',
                    'arrive' => '1643-06-15',
                    'wp' => [22, 44],
                ],
            ],
            'unknown' => [
                [
                    [143, -39.4],
                    [149.6, -39.4],
                    [149.6, -44.6],
                    [143, -44.6],
                    [143, -39.4],
                ],
                [
                    [164.5, -33],
                    [179.8, -33],
                    [179.8, -48.5],
                    [164.5, -48.5],
                    [164.5, -33],
                ],
                [
                    [162.5, -23.2],
                    [169, -23.2],
                    [169, -19.4],
                    [162.5, -19.4],
                    [162.5, -23.2],
                ],
                [
                    [175, -19.8],
                    [180, -19.8],
                    [180, -15.3],
                    [175, -15.3],
                    [175, -19.8],
                ],
            ],
        ],
        'voyage_view' => 'flat',
    ],
    'scenes' => [
        [
            'type' => 'voyage',
            'voyage' => 'tasman-1642',
            'leg' => 5,
            'view' => 'flat',
            'extra_config' => [
                'transition' => [
                    'type' => 'crossfade',
                    'duration' => 1.2,
                    'ease' => 'exit',
                ],
                'overview' => true,
                'overview_anim' => [
                    'route' => 'draw',
                    'duration' => 4.5,
                    'stops' => true,
                ],
                'match_target' => [
                    'core' => [],
                    'themes' => [],
                    'actor_qids' => [],
                    'era' => null,
                    'regions' => ['european'],
                    'sig' => 'e8deefd77cfaad6f5352af2a5578ec65',
                ],
            ],
            'shots' => [
                [
                    'order' => 0,
                    'layers' => [
                        [
                            'asset_id' => 1,
                            'path' => 'lessons/18/paintings/layer-commons-f21e25368822.jpg',
                            'kind' => 'figure',
                            'depth' => 1.3,
                            'scale' => 0.885,
                            'height' => 40,
                            'sway' => false,
                            'x' => 22.62,
                            'y' => 62.3,
                            'blend' => 'darken',
                            'opacity' => 1,
                        ],
                    ],
                ],
            ],
        ],
        [
            'type' => 'voyage',
            'location' => 'Mauritius',
            'voyage' => 'tasman-1642',
            'leg' => 0,
            'view' => 'flat',
            'intro' => true,
            'title' => 'Verversingspost',
            'date_label' => '5 september 1642',
            'story' => 'Mauritius was voor de VOC een vitale verversingspost waar schepen vers water en voedsel konden laden. Tasmans mannen werkten koortsachtig: het dek werd geschrobd, zeilen gerepareerd, vaten gevuld met water en vlees. Na twee maanden koersten ze op 8 oktober 1642 koers naar het zuiden.',
            'images' => [
                [
                    'url' => '/lessons/tasman/mauritius-voc.jpg',
                    'credit' => 'Fort Mauritius on Makian',
                ],
                [
                    'url' => '/lessons/tasman/vloot-rennefeld.webp',
                    'credit' => 'De vloot van Abel Tasman (Johannes Rennefeld, gravure)',
                ],
                [
                    'url' => '/lessons/tasman/voc-schip-dodo.jpg',
                    'credit' => 'Dodo (VOC Gelderland, 1602)',
                ],
            ],
        ],
        [
            'type' => 'voyage',
            'location' => 'Van Diemensland (Tasmanië)',
            'voyage' => 'tasman-1642',
            'leg' => 1,
            'view' => 'flat',
            'title' => 'Land van Van Diemen',
            'date_label' => '24 november 1642',
            'story' => 'Op 24 november 1642 zagen Tasmans mannen voor het eerst een onbekend, bergachtig eiland. Ze noemden het naar gouverneur-generaal Antonio van Diemen. Terukkeerend naar boord ontdekten zij dik bos en rooksporen van vuur, maar geen mensen. Het eiland zou later \'Tasmania\' heten.',
            'images' => [
                [
                    'url' => '/lessons/tasman/kaart-tasman-1644.jpg',
                    'credit' => 'Tasmanmap1644',
                ],
                [
                    'url' => '/lessons/tasman/tasman-gravure-1886.webp',
                    'credit' => 'Abel Janszoon Tasman, houtgravure (Andrew Garran, 1886)',
                ],
                [
                    'url' => '/lessons/tasman/kaart-tasman-reizen.jpg',
                    'credit' => 'Kaart van de reizen van Abel Tasman',
                ],
            ],
        ],
        [
            'type' => 'voyage',
            'location' => 'Moordenaarsbaai (Golden Bay, Nieuw-Zeeland)',
            'voyage' => 'tasman-1642',
            'leg' => 2,
            'view' => 'flat',
            'title' => 'Eerste contact gaat tragisch',
            'date_label' => '13 december 1642',
            'story' => 'Op 13 december 1642 voeren Tasmans schepen langs Nieuw-Zeeland. Twee dagen later zagen zij gekleurde kano\'s vol Māori-krijgers. Toen een sloep van Tasman probeerde contact te maken, werd zij geramd en ramde een kano erin. Vier Nederlandse matrozen verdronken. Tasman noemde dit water Moordenaarsbaai.',
            'images' => [
                [
                    'url' => '/lessons/tasman/moordenaarsbaai-gilsemans.jpg',
                    'credit' => 'Gilsemans 1642',
                ],
                [
                    'url' => '/lessons/tasman/golden-bay-encounter.png',
                    'credit' => 'Tasman\'s 1642 encounter with the Maori at Golden Bay, New Zealand',
                ],
                [
                    'url' => '/lessons/tasman/murderers-bay-sketch.webp',
                    'credit' => 'Gezicht op de Moordenaarsbaai, december 1642 (schets)',
                ],
            ],
        ],
        [
            'type' => 'voyage',
            'location' => 'Tonga',
            'voyage' => 'tasman-1642',
            'leg' => 3,
            'view' => 'flat',
            'title' => 'Vriendelijk welkom',
            'date_label' => '21 januari 1643',
            'story' => 'Op 21 januari 1643 arriveerde Tasman in Tonga. Hier verliep alles anders: vriendelijke kano\'s vol vrouwen en mannen naderden de schepen met varkens, kokosnoten en verse vruchten. De VOC-mannen gaven spijkers, glaswerk en zilverdraad in ruil. Dit was een volkomen ander ontvangst dan Nieuw-Zeeland.',
            'images' => [
                [
                    'url' => '/lessons/tasman/voc-schepen.png',
                    'credit' => 'Dutch flute Zeehaen and war yacht Heemskerck',
                ],
                [
                    'url' => '/lessons/tasman/duyfken-replica.jpg',
                    'credit' => 'Duyfken replica of Dutch ship at Denham shark bay',
                ],
                [
                    'url' => '/lessons/tasman/tasman-portret-cuyp.jpg',
                    'credit' => 'Abel Tasman - Cuyp (cropped)',
                ],
            ],
        ],
        [
            'type' => 'voyage',
            'location' => 'Batavia',
            'voyage' => 'tasman-1642',
            'leg' => 4,
            'view' => 'flat',
            'title' => 'Thuiskomst met geheimen',
            'date_label' => '15 juni 1643',
            'story' => 'Na nog een volle maand zeilen door onbekende wateren bereikten Tasmans twee schepen op 15 juni 1643 Batavia. De gouverneur-generaal was niet erg blij: geen goud, geen schatten, geen handelsouten. Maar Tasman had iets oneindig veel waardevollers gegeven: de eerste nauwkeurige kaarten van grote delen van de wereld.',
        ],
    ],
];
