#!/usr/bin/env bash
#
# Copy generated public/ assets that git does not carry.
#
# scripts/deploy-prod.sh ships `git archive HEAD`, so anything gitignored is simply absent from the
# deploy — silently, with no error. That is how /flags/manifest.json and 1,690 flag PNGs came to 404
# on production while the Time-Map asked for them on every load (resources/js/timemap/index.js:254
# and :295). Nothing failed; the files had just never left the laptop.
#
# These directories are BUILD OUTPUT, regenerated by artisan commands, and run to tens of megabytes.
# Committing them would bloat the repo for no benefit, so they travel separately — the same split
# scripts/sync-narrator-media.sh makes for storage/.
#
# Usage:  scripts/sync-public-assets.sh [--dry-run]
#
set -euo pipefail

HOST="u2628-emomoo15slu6@ssh.historyportal.eu"
PORT=18765
KEY="$HOME/.ssh/siteground_tlp2"
DRY=""

[[ "${1:-}" == "--dry-run" ]] && DRY="--dry-run"

cd "$(dirname "$0")/.."

# Found, not assumed: the site directory is named after the primary domain, which has moved.
APP=$(ssh -p "$PORT" -i "$KEY" "$HOST" \
  "for d in www/*/app; do [ -f \"\$d/artisan\" ] && [ ! -L \"\$(dirname \"\$d\")\" ] && { echo \"\$d\"; exit; }; done" \
  2>/dev/null | head -1 | tr -d '\r')
if [[ -z "$APP" ]]; then
  echo "✗ could not find the app on the server. Refusing to sync." >&2
  exit 1
fi

# Gitignored, generated, and requested by the running app. Each one is a 404 in production if absent.
#   flags            — timemap/index.js loads /flags/{qid}.png and /flags/manifest.json
#   cliopatria-tiles — historical border tiles for the Time-Map
#   coast-echo-tiles — coastline echo layer
DIRS=(flags cliopatria-tiles coast-echo-tiles)

for dir in "${DIRS[@]}"; do
  if [[ ! -d "public/$dir" ]]; then
    echo "▸ skip $dir (nothing local to send)"
    continue
  fi
  echo "▸ $dir ($(du -sh "public/$dir" | cut -f1))"
  # NO --delete. Production may hold tiles generated there that this machine has never built, and
  # taking them because the local copy is thinner would break the map to tidy a directory.
  ssh -p "$PORT" -i "$KEY" "$HOST" "mkdir -p '$APP/public/$dir'"
  rsync -az $DRY --itemize-changes \
    -e "ssh -p $PORT -i $KEY" \
    "public/$dir/" "$HOST:$APP/public/$dir/" | tail -5
done

[[ -n "$DRY" ]] && { echo "▸ dry run only, nothing changed"; exit 0; }

echo "▸ verifying a real file over HTTP, because a copy that landed unreadable is still a 404"
SITE=$(ssh -p "$PORT" -i "$KEY" "$HOST" "cd $APP && php -r \"
  foreach (file('.env', FILE_IGNORE_NEW_LINES) as \\\$l) {
    if (preg_match('/^APP_URL=(.+)\\\$/', \\\$l, \\\$m)) { echo trim(\\\$m[1], '\\\"'); break; }
  }\"" 2>/dev/null | tail -1 | tr -d '\r')
for path in "flags/manifest.json"; do
  echo "  $path -> $(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "$SITE/$path")"
done
